sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  # Install Docker Compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

script:
  - docker-compose build
