version: '2'

services:
  front:
    build:
      context: .
      args:
        adminuser: "admin"
        adminpass: "pass"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    links:
      - mysql:mysqlcontainer
      - memcached:memcached
    volumes:
      - ./www:/var/www
      - ./logs:/var/log/supervisor

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  memcached:
    image: memcached
    ports:
      - "11211:11211"

